import "~/styles/globals.css";

import { type Metadata } from "next";
import { Manrope } from "next/font/google";

import { UserPreferencesProvider } from "~/contexts/user-preferences-context";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body>
        <UserPreferencesProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </UserPreferencesProvider>
      </body>
    </html>
  );
}
